### ISSUE TITLE
Boden Sprites nicht im GIT

### ISSUE THREAD

**Issue by steima** [simsonimus/Diplomarbeit#1]
Spiel läuft bei mir super nur der Sprite für den Boden wird nicht angezeigt. Eventuell nicht im GIT?

**Comment by steima** [comment]
![screen shot 2015-08-07 at 9 27 24](https://cloud.githubusercontent.com/assets/4509240/9130854/91b62664-3ce6-11e5-8682-4ceec4a552d2.png)

**Comment by simsonimus** [comment]
Soll angeblich Fehler des gitignores gewesen sein. Bitte probieren ob es nun funktioniert.

**Comment by steima** [comment]
Der GrassThinSprite ist bei mir da, aber wird nicht angezeigt. Vielleicht liegt es an meiner neueren Unity Version

**Comment by simsonimus** [comment]
Bitte pullen, und dann nochmal probieren
