### ISSUE TITLE
Wiederverwendung der Vogel Sprites

### ISSUE THREAD

**Issue by steima** [simsonimus/Diplomarbeit#2]
Das dürfte irgendwie nicht klappen wenn ich das Spiel bei mir laufen lasse wird die Liste der Vogel1 Clone immer länger. Vielleicht kann man eine Liste der unbenutzten Vögel anlegen und nur dann einen neuen erzeugen wenn in der Liste kein freier ist.
![screen shot 2015-08-07 at 9 30 07](https://cloud.githubusercontent.com/assets/4509240/9130909/0f7ecd8a-3ce7-11e5-88fc-bde103ec2f3c.png)

**Comment by simsonimus** [comment]
Collision System geupdatet
